@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/chat/message/user/<receiverId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "6552ec109648cd25091f465f",
  "receiverId": "6552ea0fe697b029b526519d",
  "receiverUsername": "Tepu",
  "receiverAvatarColor": "red",
  "receiverProfilePicture": "https://res.cloudinary.com/de0llaul4/image/upload/v1699803288/6550f096234925f365996e4b",
  "body": "Yo! 2nd message",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "6552e9fee697b029b5265196",
  "userTwo": "6552ea0fe697b029b526519d"
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "6550f07d234925f365996e43",
  "userTwo": "6550f0b2234925f365996e59"
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "6552e9fee697b029b5265196",
  "receiverId": "6552ea0fe697b029b526519d"
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

# For this endpoint, the type is either add or remove
{
  "conversationId": "6552ec109648cd25091f465f",
  "messageId": "6552ec109648cd25091f465e",
  "reaction": "love",
  "type": "add"
}

###
DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/6552ec109648cd25091f465e/6552e9fee697b029b5265196/6552ea0fe697b029b526519d/deleteForEveryone
#/chat/message/mark-as-deleted/<messageId>/<senderId>/<receiverId>/<type>
# For this endpoint, the type is either deleteForMe or deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true



