@baseUrl = http://localhost:5000

@urlPath = api/v1


###
PUT {{baseUrl}}/{{urlPath}}/notification/65511310140f99839bd40a4b
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###
DELETE {{baseUrl}}/{{urlPath}}/notification/65511310140f99839bd40a4b
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###
GET {{baseUrl}}/{{urlPath}}/notifications
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
